name: Send Test Email

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_TO_ADDRESS: ${{ secrets.EMAIL_TO_ADDRESS }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SUBJECT_LINE: "camply test email"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install camply
        run: pip install "git+https://github.com/juftin/camply.git@refs/pull/378/head"

      - name: Send a test notification
        run: camply test-notifications --notifications email
